@startuml
start
:Create LocationsNeedingClearance iterator;
while (Iterator has next location?) is (yes)
  :Read next Location;
  if (Location cleared?) then (no)
    :Clear location for shooting;
  else (yes)
  endif
endwhile (no)
:Film confirms areas;
if (Crew iterator finds everyone present?) then (yes)
  :Transition to ReadyForShoot;
else (no)
  :Remain PendingAreaConfirmation;
endif
stop
@enduml