@startuml
[*] --> Initial
Initial --> PendingAreaConfirmation : confirmAreas()
PendingAreaConfirmation --> ReadyForShoot : all locations cleared
PendingAreaConfirmation --> PendingAreaConfirmation : clearance missing
ReadyForShoot --> Shooting : startShooting()
Shooting --> VIPMissing : VIP absent
Shooting --> OtherMissing : other crew absent
VIPMissing --> Shooting : VIP returns
OtherMissing --> VIPMissing : VIP absent
OtherMissing --> Shooting : crew returns
Shooting --> Finished : all locations filmed
Finished --> [*]
@enduml